##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR $GOPATH/src/github.com/schwarzlichtbezirk/dfs/
COPY . .
RUN go mod download

RUN go build -o /go/bin/node ./node

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

ENV DFSNODEPORT=50051

COPY --from=build /go/bin/node /go/bin/node

EXPOSE ${DFSNODEPORT}

USER nonroot:nonroot

ENTRYPOINT ["/go/bin/node"]
