##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR $GOPATH/src/github.com/schwarzlichtbezirk/dfs/
COPY . .
RUN go mod download

RUN go build -o /go/bin/front ./front

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

COPY --from=build /go/bin/front /go/bin/front
COPY --from=build /go/src/github.com/schwarzlichtbezirk/dfs/config/*.yaml /go/bin/dfs-config/

EXPOSE 8008 8010

USER nonroot:nonroot

ENTRYPOINT ["/go/bin/front"]
