# distributed file server frontend configuration file,
# used in read-only mode on service initialization.

webserver: # See https://golang.org/pkg/net/http/#Server for details.
    # List of address:port values for non-encrypted connections.
    # Address is skipped in most common cases, port only remains.
    port-http:
        - :8008
        - :8010
    # Maximum duration for reading the entire request, including the body.
    read-timeout: 15s
    # Amount of time allowed to read request headers.
    read-header-timeout: 15s
    # Maximum duration before timing out writes of the response.
    write-timeout: 15s
    # Maximum amount of time to wait for the next request when keep-alives are enabled.
    idle-timeout: 60s
    # Controls the maximum number of bytes the server will read parsing
    # the request header's keys and values, including the request line, in bytes.
    max-header-bytes: 1048576 # 1M
    # Maximum duration to wait for graceful shutdown.
    shutdown-timeout: 15s
storage:
    # Points to fill nodes by fluid algorithm.
    node-fluid-fill: true
    # Minimum size of chunk to divide the file and put to nodes, except last chunk.
    min-node-chunk-size: 4096 # 4K
    # Maximum chunk size to send to each node during the streaming.
    stream-chunk-size: 1024
    # gRPC API call timeout.
    api-timeout: 2s
node-list: # Distributed file server list of nodes.
    - localhost:50051
    - localhost:50052
