// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: dfs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataGuideClient is the client API for DataGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGuideClient interface {
	// Read creates reading streaming by dividing big chunk to serie of small chunks.
	Read(ctx context.Context, in *Range, opts ...grpc.CallOption) (*Chunk, error)
	// Write receives serie of small chunks and glue them into big one.
	Write(ctx context.Context, opts ...grpc.CallOption) (DataGuide_WriteClient, error)
	// GetRange returns bounds of stored file chunk.
	// Returns empty struct if no such chunk is present.
	GetRange(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*Range, error)
	// Remove deletes file chunks.
	Remove(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*Range, error)
	// Purge deleted all file chunks.
	Purge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type dataGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGuideClient(cc grpc.ClientConnInterface) DataGuideClient {
	return &dataGuideClient{cc}
}

func (c *dataGuideClient) Read(ctx context.Context, in *Range, opts ...grpc.CallOption) (*Chunk, error) {
	out := new(Chunk)
	err := c.cc.Invoke(ctx, "/dfs.DataGuide/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGuideClient) Write(ctx context.Context, opts ...grpc.CallOption) (DataGuide_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataGuide_ServiceDesc.Streams[0], "/dfs.DataGuide/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataGuideWriteClient{stream}
	return x, nil
}

type DataGuide_WriteClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*Summary, error)
	grpc.ClientStream
}

type dataGuideWriteClient struct {
	grpc.ClientStream
}

func (x *dataGuideWriteClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataGuideWriteClient) CloseAndRecv() (*Summary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Summary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataGuideClient) GetRange(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*Range, error) {
	out := new(Range)
	err := c.cc.Invoke(ctx, "/dfs.DataGuide/GetRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGuideClient) Remove(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*Range, error) {
	out := new(Range)
	err := c.cc.Invoke(ctx, "/dfs.DataGuide/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGuideClient) Purge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/dfs.DataGuide/Purge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGuideServer is the server API for DataGuide service.
// All implementations must embed UnimplementedDataGuideServer
// for forward compatibility
type DataGuideServer interface {
	// Read creates reading streaming by dividing big chunk to serie of small chunks.
	Read(context.Context, *Range) (*Chunk, error)
	// Write receives serie of small chunks and glue them into big one.
	Write(DataGuide_WriteServer) error
	// GetRange returns bounds of stored file chunk.
	// Returns empty struct if no such chunk is present.
	GetRange(context.Context, *FileID) (*Range, error)
	// Remove deletes file chunks.
	Remove(context.Context, *FileID) (*Range, error)
	// Purge deleted all file chunks.
	Purge(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedDataGuideServer()
}

// UnimplementedDataGuideServer must be embedded to have forward compatible implementations.
type UnimplementedDataGuideServer struct {
}

func (UnimplementedDataGuideServer) Read(context.Context, *Range) (*Chunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedDataGuideServer) Write(DataGuide_WriteServer) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedDataGuideServer) GetRange(context.Context, *FileID) (*Range, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRange not implemented")
}
func (UnimplementedDataGuideServer) Remove(context.Context, *FileID) (*Range, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedDataGuideServer) Purge(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Purge not implemented")
}
func (UnimplementedDataGuideServer) mustEmbedUnimplementedDataGuideServer() {}

// UnsafeDataGuideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGuideServer will
// result in compilation errors.
type UnsafeDataGuideServer interface {
	mustEmbedUnimplementedDataGuideServer()
}

func RegisterDataGuideServer(s grpc.ServiceRegistrar, srv DataGuideServer) {
	s.RegisterService(&DataGuide_ServiceDesc, srv)
}

func _DataGuide_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Range)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGuideServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfs.DataGuide/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGuideServer).Read(ctx, req.(*Range))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGuide_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataGuideServer).Write(&dataGuideWriteServer{stream})
}

type DataGuide_WriteServer interface {
	SendAndClose(*Summary) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type dataGuideWriteServer struct {
	grpc.ServerStream
}

func (x *dataGuideWriteServer) SendAndClose(m *Summary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataGuideWriteServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataGuide_GetRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGuideServer).GetRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfs.DataGuide/GetRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGuideServer).GetRange(ctx, req.(*FileID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGuide_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGuideServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfs.DataGuide/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGuideServer).Remove(ctx, req.(*FileID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGuide_Purge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGuideServer).Purge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfs.DataGuide/Purge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGuideServer).Purge(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGuide_ServiceDesc is the grpc.ServiceDesc for DataGuide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGuide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.DataGuide",
	HandlerType: (*DataGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _DataGuide_Read_Handler,
		},
		{
			MethodName: "GetRange",
			Handler:    _DataGuide_GetRange_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DataGuide_Remove_Handler,
		},
		{
			MethodName: "Purge",
			Handler:    _DataGuide_Purge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _DataGuide_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dfs.proto",
}
