// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.14.0
// source: dfs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataGuideClient is the client API for DataGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGuideClient interface {
	Write(ctx context.Context, opts ...grpc.CallOption) (DataGuide_WriteClient, error)
}

type dataGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGuideClient(cc grpc.ClientConnInterface) DataGuideClient {
	return &dataGuideClient{cc}
}

func (c *dataGuideClient) Write(ctx context.Context, opts ...grpc.CallOption) (DataGuide_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataGuide_ServiceDesc.Streams[0], "/dfs.DataGuide/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataGuideWriteClient{stream}
	return x, nil
}

type DataGuide_WriteClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*Summary, error)
	grpc.ClientStream
}

type dataGuideWriteClient struct {
	grpc.ClientStream
}

func (x *dataGuideWriteClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataGuideWriteClient) CloseAndRecv() (*Summary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Summary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataGuideServer is the server API for DataGuide service.
// All implementations must embed UnimplementedDataGuideServer
// for forward compatibility
type DataGuideServer interface {
	Write(DataGuide_WriteServer) error
	mustEmbedUnimplementedDataGuideServer()
}

// UnimplementedDataGuideServer must be embedded to have forward compatible implementations.
type UnimplementedDataGuideServer struct {
}

func (UnimplementedDataGuideServer) Write(DataGuide_WriteServer) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedDataGuideServer) mustEmbedUnimplementedDataGuideServer() {}

// UnsafeDataGuideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGuideServer will
// result in compilation errors.
type UnsafeDataGuideServer interface {
	mustEmbedUnimplementedDataGuideServer()
}

func RegisterDataGuideServer(s grpc.ServiceRegistrar, srv DataGuideServer) {
	s.RegisterService(&DataGuide_ServiceDesc, srv)
}

func _DataGuide_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataGuideServer).Write(&dataGuideWriteServer{stream})
}

type DataGuide_WriteServer interface {
	SendAndClose(*Summary) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type dataGuideWriteServer struct {
	grpc.ServerStream
}

func (x *dataGuideWriteServer) SendAndClose(m *Summary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataGuideWriteServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataGuide_ServiceDesc is the grpc.ServiceDesc for DataGuide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGuide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.DataGuide",
	HandlerType: (*DataGuideServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _DataGuide_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dfs.proto",
}
